import type { BiomarkersPresentation } from "./biomarkers-presentation";
import type { BiomarkersPresentationState } from "./biomarkers-presentation-state";

export const sampleBiomarkersPresentation: BiomarkersPresentation = {
  title: "Wyniki badań",
  statusLabel: "Twoje wyniki są uporządkowane i gotowe do przeglądu.",
  completenessLabel: "Jakość importu danych: 100%",
  latestCollectionLabel: "Ostatnie badanie: 2026-08-01",
  attentionCount: 0,
  unresolvedCount: 0,
  limitations: [],
  summary: {
    totalReports: 2,
    activeReports: 2,
    totalObservations: 6,
    verifiedObservations: 6,
    unresolvedObservations: 0,
    possibleDuplicates: 0,
    latestCollectionDate: "2026-08-01",
  },
  categories: [
    {
      categoryCode: "iron_panel",
      displayName: "Gospodarka żelazowa",
      attentionCount: 0,
      unresolvedCount: 0,
      biomarkers: [
        {
          code: "ferritin",
          name: "Ferrytyna",
          valueLabel: "35",
          unitLabel: "µg/L",
          referenceLabel: "Norma lab: 30-200",
          collectedAtLabel: "1 sie 2026",
          trendLabel: "Bez wyraźnej zmiany",
          trendDirection: "stable",
          laboratoryFlag: null,
          verificationLabel: "Zweryfikowano",
          limitations: [],
        },
        {
          code: "iron",
          name: "Żelazko w surowicy",
          valueLabel: "115",
          unitLabel: "µg/dL",
          referenceLabel: "Norma lab: 65-175",
          collectedAtLabel: "1 sie 2026",
          trendLabel: "Rośnie",
          trendDirection: "increasing",
          laboratoryFlag: null,
          verificationLabel: "Zweryfikowano",
          limitations: [],
        },
      ],
    },
    {
      categoryCode: "morphology",
      displayName: "Morfologia",
      attentionCount: 0,
      unresolvedCount: 0,
      biomarkers: [
        {
          code: "hemoglobin",
          name: "Hemoglobina",
          valueLabel: "142",
          unitLabel: "g/L",
          referenceLabel: "Norma lab: 135-175",
          collectedAtLabel: "1 sie 2026",
          trendLabel: "Rośnie",
          trendDirection: "increasing",
          laboratoryFlag: null,
          verificationLabel: "Zweryfikowano",
          limitations: [],
        },
        {
          code: "wbc",
          name: "Leukocyty (WBC)",
          valueLabel: "6.2",
          unitLabel: "10^9/L",
          referenceLabel: "Norma lab: 4.0-10.0",
          collectedAtLabel: "1 sie 2026",
          trendLabel: "Maleje",
          trendDirection: "decreasing",
          laboratoryFlag: null,
          verificationLabel: "Zweryfikowano",
          limitations: [],
        },
      ],
    },
    {
      categoryCode: "vitamins",
      displayName: "Witaminy i Minerały",
      attentionCount: 0,
      unresolvedCount: 0,
      biomarkers: [
        {
          code: "vitamin_d3",
          name: "Witamina 25(OH)D",
          valueLabel: "48.5",
          unitLabel: "ng/mL",
          referenceLabel: "Norma lab: 30-80",
          collectedAtLabel: "1 sie 2026",
          trendLabel: "Rośnie",
          trendDirection: "increasing",
          laboratoryFlag: null,
          verificationLabel: "Zweryfikowano",
          limitations: [],
        },
        {
          code: "b12_qualitative",
          name: "Status Witaminy B12",
          valueLabel: "Prawidłowy",
          unitLabel: "",
          referenceLabel: "Wynik jakościowy",
          collectedAtLabel: "1 sie 2026",
          trendLabel: "Brak trendu",
          trendDirection: "unavailable",
          laboratoryFlag: null,
          verificationLabel: "Zweryfikowano",
          limitations: [],
        },
      ],
    },
  ],
  unresolvedItems: [],
};

export const samplePartialBiomarkersPresentation: BiomarkersPresentation = {
  ...sampleBiomarkersPresentation,
  statusLabel: "Częściowe dane laboratoryjne",
  completenessLabel: "Jakość importu danych: 75%",
  attentionCount: 1,
  unresolvedCount: 1,
  limitations: [
    "1 nierozpoznana pozycja laboratoryjna wymaga ręcznej weryfikacji.",
    "Wykryto 1 potencjalny duplikat raportu laboratoryjnego.",
  ],
  summary: {
    ...sampleBiomarkersPresentation.summary,
    totalObservations: 6,
    verifiedObservations: 5,
    unresolvedObservations: 1,
    possibleDuplicates: 1,
  },
  unresolvedItems: [
    {
      id: "obs-unres-preview-1",
      name: "Nierozpoznany Marker Syntetyczny",
      unit: "U/L",
      collectedAtLabel: "1 sie 2026",
      reason: "Brak jednoznacznego dopasowania w rejestrze biomarkerów.",
    },
  ],
};

export const biomarkersPreviewStates: Record<BiomarkersPresentationState["kind"], BiomarkersPresentationState> = {
  ready: {
    kind: "ready",
    presentation: sampleBiomarkersPresentation,
  },
  partial: {
    kind: "partial",
    presentation: samplePartialBiomarkersPresentation,
    message: "Część wyników wymaga uzupełnienia lub weryfikacji.",
    limitations: samplePartialBiomarkersPresentation.limitations,
  },
  unavailable: {
    kind: "unavailable",
    title: "Wyniki badań",
    message: "Nie masz jeszcze dodanych wyników badań.",
    reason: "Po dodaniu raportu zobaczysz historię i zmiany biomarkerów.",
    nextAction: "Dodaj wyniki",
  },
  stale: {
    kind: "stale",
    presentation: sampleBiomarkersPresentation,
    message: "Widok danych nie był ostatnio odświeżany.",
    lastUpdatedText: "Ostatnia aktualizacja: 1 sie 2026, 08:00.",
  },
  loading: {
    kind: "loading",
    message: "Wczytywanie wyników badań...",
  },
  failure: {
    kind: "failure",
    title: "Błąd odczytu",
    message: "Nie udało się pobrać wyników badań.",
    supportingText: "Wystąpił problem techniczny podczas pobierania danych.",
    retryLabel: "Spróbuj ponownie",
  },
};
