from decision.models import DecisionResult

from planner.models import PlannedWorkout

from workout.blocks import WorkoutBlock
from workout.models import Workout


class WorkoutBuilder:

    def build(
        self,
        decision: DecisionResult,
        planned: PlannedWorkout,
    ) -> Workout:

        blocks = []

        for block in planned.blocks:

            blocks.append(

                WorkoutBlock(

                    name=block.name,

                    duration=block.duration,

                    power_from=block.power_from,

                    power_to=block.power_to,

                    cadence_from=block.cadence_from,

                    cadence_to=block.cadence_to,

                    repeat=block.repeat,

                    description="",

                )

            )

        return Workout(

            #
            # Identity
            #

            name=planned.name,

            goal=decision.recommendation,

            description="Generated by Athlete Platform",

            #
            # Targets
            #

            duration=planned.estimated_duration,

            target_tss=planned.target_tss,

            target_if=0.0,

            #
            # Structure
            #

            blocks=blocks,

        )